set ProjectRoot=..\..\
set ToolDir=%ProjectRoot%tools\
set ProgDir=%ProjectRoot%mod\
set IntDir=%ProjectRoot%build\qvm\
set LCC=%ToolDir%q3lcc.exe -DQ3_VM -DQC=1 -DUNLAGGED=1 -S -Wf-target=bytecode -Wf-g -I%ProgDir%code\cgame -I%ProgDir%code\qcommon -I%ProgDir%code\game -I%ProgDir%code\hudlib
set Q3ASM=%ToolDir%q3asm.exe

%LCC% %ProgDir%code\cgame\cg_consolecmds.c
%LCC% %ProgDir%code\cgame\cg_draw.c
%LCC% %ProgDir%code\cgame\cg_drawtools.c
%LCC% %ProgDir%code\cgame\cg_effects.c
%LCC% %ProgDir%code\cgame\cg_ents.c
%LCC% %ProgDir%code\cgame\cg_event.c
%LCC% %ProgDir%code\cgame\cg_info.c
%LCC% %ProgDir%code\cgame\cg_localents.c
%LCC% %ProgDir%code\cgame\cg_main.c
%LCC% %ProgDir%code\cgame\cg_marks.c
%LCC% %ProgDir%code\cgame\cg_particles.c
%LCC% %ProgDir%code\cgame\cg_players.c
%LCC% %ProgDir%code\cgame\cg_playerstate.c
%LCC% %ProgDir%code\cgame\cg_predict.c
%LCC% %ProgDir%code\cgame\cg_scoreboard.c
%LCC% %ProgDir%code\cgame\cg_servercmds.c
%LCC% %ProgDir%code\cgame\cg_snapshot.c
%LCC% %ProgDir%code\cgame\cg_view.c
%LCC% %ProgDir%code\cgame\cg_weapons.c
%LCC% %ProgDir%code\game\bg_lib.c
%LCC% %ProgDir%code\game\bg_misc.c
%LCC% %ProgDir%code\game\bg_pmove.c
%LCC% %ProgDir%code\game\bg_slidemove.c
%LCC% %ProgDir%code\qcommon\q_math.c
%LCC% %ProgDir%code\qcommon\q_shared.c
%LCC% %ProgDir%code\cgame\cg_champions.c
%LCC% %ProgDir%code\cgame\cg_damageplum.c
%LCC% %ProgDir%code\cgame\cg_decals.c
%LCC% %ProgDir%code\cgame\cg_dmgdir.c
%LCC% %ProgDir%code\cgame\cg_hud.c
%LCC% %ProgDir%code\cgame\cg_unlagged.c
%LCC% %ProgDir%code\cgame\hud_ability.c
%LCC% %ProgDir%code\cgame\hud_ammo.c
%LCC% %ProgDir%code\cgame\hud_crosshair.c
%LCC% %ProgDir%code\cgame\hud_deathmessage.c
%LCC% %ProgDir%code\cgame\hud_ffa_scores.c
%LCC% %ProgDir%code\cgame\hud_fragmessage.c
%LCC% %ProgDir%code\cgame\hud_obituary.c
%LCC% %ProgDir%code\cgame\hud_pickups.c
%LCC% %ProgDir%code\cgame\hud_playerstatus.c
%LCC% %ProgDir%code\cgame\hud_shared.c
%LCC% %ProgDir%code\cgame\hud_tdm_scores.c
%LCC% %ProgDir%code\cgame\hud_timer.c
%LCC% %ProgDir%code\cgame\hud_tournament_scores.c
%LCC% %ProgDir%code\game\bg_champions.c
%LCC% %ProgDir%code\game\bg_promode.c
%LCC% %ProgDir%code\hudlib\hudlib.c

%Q3ASM% -f cgame
