// font_qcde

static font_t font_qcde = {
    .hdr = {
        .name = "hud/font_qcde",
        .line_height = 56,
        .base = 56,
        .scale_w = 256,
        .scale_h = 256,
        .num_chars = 17,
    },
    .chars = {
        { .id = 37, .x = 46, .y = 0, .width = 41, .height = 56, .xoffset = 0, .yoffset = 0, .xadvance = 41 + 7 }, 
        { .id = 42, .x = 89, .y = 0, .width = 41, .height = 56, .xoffset = 0, .yoffset = 0, .xadvance = 41 + 7 }, 
        { .id = 43, .x = 132, .y = 0, .width = 41, .height = 56, .xoffset = 0, .yoffset = 0, .xadvance = 41 + 7 },
        { .id = 46, .x = 242, .y = 0, .width = 12, .height = 56, .xoffset = 0, .yoffset = 0, .xadvance = 12 + 7 },
        { .id = 47, .x = 43, .y = 116, .width = 20, .height = 56, .xoffset = 0, .yoffset = 0, .xadvance = 20 + 7 },
        { .id = 48, .x = 175, .y = 0, .width = 41, .height = 56, .xoffset = 0, .yoffset = 0, .xadvance = 41 + 7 },
        { .id = 49, .x = 218, .y = 0, .width = 22, .height = 56, .xoffset = 0, .yoffset = 0, .xadvance = 22 + 7 },
        { .id = 50, .x = 0, .y = 58, .width = 41, .height = 56, .xoffset = 0, .yoffset = 0, .xadvance = 41 + 7 },
        { .id = 51, .x = 43, .y = 58, .width = 41, .height = 56, .xoffset = 0, .yoffset = 0, .xadvance = 41 + 7 },
        { .id = 52, .x = 0, .y = 0, .width = 44, .height = 56, .xoffset = 0, .yoffset = 0, .xadvance = 44 + 7 },
        { .id = 53, .x = 86, .y = 58, .width = 41, .height = 56, .xoffset = 0, .yoffset = 0, .xadvance = 41 + 7 },
        { .id = 54, .x = 129, .y = 58, .width = 41, .height = 56, .xoffset = 0, .yoffset = 0, .xadvance = 41 + 7 },
        { .id = 55, .x = 215, .y = 58, .width = 39, .height = 56, .xoffset = 0, .yoffset = 0, .xadvance = 39 + 7 },
        { .id = 56, .x = 172, .y = 58, .width = 41, .height = 56, .xoffset = 0, .yoffset = 0, .xadvance = 41 + 7 },
        { .id = 57, .x = 0, .y = 116, .width = 41, .height = 56, .xoffset = 0, .yoffset = 0, .xadvance = 41 + 7 },
        { .id = 58, .x = 65, .y = 116, .width = 12, .height = 56, .xoffset = 0, .yoffset = 0, .xadvance = 12 + 7 },
        { .id = 64, .x = 79, .y = 116, .width = 77, .height = 49, .xoffset = 0, .yoffset = 0, .xadvance = 77 + 7 },
    },
};
